### ISSUE TITLE
py4j.Py4JException: Method getDeployingNodePC([]) does not exist

### ISSUE THREAD

**Issue by mtu95** [labs4capella/python4capella#105]
Hello,
I got the follow message when I try to apply the method getDeployingNodePC() to behaviorPC.  Could you please check it ? 
py4j.Py4JException: Method getDeployingNodePC([]) does not exist

Context: Get the deploying node PC from the 'deployed behavior PC' in physical architecture. 

if isinstance(elem, BehaviorPC):
        n_target = elem.get_deploying_node_p_c()

Is it a bug or am I applying it incorrectly ? Besides, in which file can i find this method ?

Thanks in advance.

**Comment by ylussaud** [comment]
Not all methods are working at the moment. you can check the status in the Word document attached to the release. In the next release you will be able to check the status directly in the documentation of the method.
The method you are looking for is in the [capella.py](https://github.com/labs4capella/python4capella/blob/7f7c1240ed44822c1263c7f51a873cab272dc6e7/plugins/Python4Capella/simplified_api/capella.py#L4769) file. In the PyDev editor you can CRTL+Click on the method call to nativage to its definition.

**Comment by ylussaud** [comment]
The getDeployingNodePC() is a Java method that we can access thanks to EASE. By default we create a call with the same name between the simplified Python API and the Java Capella API. But there are some differences and this call is one of them.
And yes the CTRL+Click on getDeployingNodePC() will not give you the declaration in the Java code and in this case the Java method doesn't exist.

If you plan to implement it in Python let me know. You can have a look at the [capella_query_by_name](https://github.com/labs4capella/python4capella/blob/7f7c1240ed44822c1263c7f51a873cab272dc6e7/plugins/Python4Capella/simplified_api/capella.py#L172) or the [capella_query](https://github.com/labs4capella/python4capella/blob/7f7c1240ed44822c1263c7f51a873cab272dc6e7/plugins/Python4Capella/simplified_api/capella.py#L190) calls to access data shown in the Capella semantic browser.

**Comment by mtu95** [comment]
Hello @ylussaud,
I've implemented the getDeployingNodePC method and it's working! I used the  capella_query_by_name.
Thank you
