### ISSUE TITLE
Launch script freeze when pandas/numpy is installed

### ISSUE THREAD

**Issue by arnauddieumegard** [labs4capella/python4capella#112]
When pandas and numpy are installed in Python4Capella Python 3.7 installation, scripts freeze at launch and nothing append.
Desinstalling pandas and numpy does fixes the problem and scripts can launch correctly.
This problem has been identified here: https://www.eclipse.org/lists/ease-dev/msg00742.html and a bug has been reported https://bugs.eclipse.org/bugs/show_bug.cgi?id=536626 with a potential workaround https://bugs.eclipse.org/bugs/show_bug.cgi?id=536626#c8 which does works.

**Comment by arnauddieumegard** [comment]
Voici le patch à appliquer
```
410,412c410,412
<     #thread = _pyease_threading.Thread(target=_pyease_watchdog, args=(engine,))
<     #thread.setDaemon(True)
<     #thread.start()
---
>     thread = _pyease_threading.Thread(target=_pyease_watchdog, args=(engine,))
>     thread.setDaemon(True)
>     thread.start()
```

**Comment by ylussaud** [comment]
This is now documented.

**Comment by mPorhel** [comment]
We have reproduced the issue with Python for Capella 1.3 / Capella 6.1 and Python for Capella 1.4 / Capella 7.0.1 when trying to import Openpyxl, but not pandas nor numpy. 
The same workaround worked.

(I had numpy installed and Openpyxl tries to load numpy if present : https://foss.heptapod.net/openpyxl/openpyxl/-/blob/branch/default/openpyxl/compat/numbers.py )

Bug [536626](https://bugs.eclipse.org/bugs/show_bug.cgi?id=536626) has been migrated to Issue [136](https://gitlab.eclipse.org/eclipse/ease/ease/-/issues/136)

A commit has been merged on the branch for EASE 0.10.0.
It applies the workaround but adds several additional fixes to terminate the python engine in a different way.

@ylussaud  do you need a dedicated ticket to see if you can apply the same commit (impacting 3 files) on the ease 0.8.0 fork for Python for Capella 1.4.x ?

**Comment by ylussaud** [comment]
That should be enough thank you.

**Comment by ylussaud** [comment]
The original patch in EASE https://gitlab.eclipse.org/eclipse/ease/ease/-/commit/c639df8efc548b2dd47f29425161cf5b217c27e3.
