### ISSUE TITLE
Fix in py4j to use Python 3.9

### ISSUE THREAD

**Issue by arnauddieumegard** [labs4capella/python4capella#119]
Hi !

For your information, I tried to use Python 3.9.12 (randomly the latest Python 3.9.x) with Python4Capella and Capella 1.4.1 and found a problem.
As is, it is not possible to use the tooling with this setup.

When launching a script I get this error message:

```
org.eclipse.ease.ScriptExecutionException: TypeError: required field "type_ignores" missing from Module
```

I looked around and found the fix https://git.eclipse.org/r/c/ease/org.eclipse.ease.core/+/153374/ related to the bug https://bugs.eclipse.org/bugs/show_bug.cgi?id=553457 fixed in ease 0.8.0.

This is working properly with this setup.

**Comment by ylussaud** [comment]
We moved to EASE 0.8.0.
