### ISSUE TITLE
Documentation: Project structure missing folders

### ISSUE THREAD

**Issue by materpillar** [labs4capella/python4capella#120]
Hi, 
the documentation states:

>###  Python4Capella project structure
>The Python4Capella project provides everything needed to interact with your Capella project from your Python scripts. 
>It contains three different folders: 
>- java_api: This folder contains the low level APIs needed to interact with the Java world. 
>- simplified_api: This folder contains the simplified APIs to interact with Capella and some of its add-ons. 
>- sample_scripts: This folder contains some sample scripts that demonstrate how you can use the simplified APIs. 

I additionally get
- resources
- utilities

**Comment by ylussaud** [comment]
Yes they have been added since:
- resources contains sample resources for the sample scripts
- utilities contains utility script that helps for interactions with Eclipse.

Thank you, we will modify the documentation.
