### ISSUE TITLE
Support of Capella 5.x

### ISSUE THREAD

**Issue by Aurelien-Pin** [labs4capella/python4capella#13]
Trying to install Python4Capella on Capella 5.0.0, we get the following error:

![installation_error](https://user-images.githubusercontent.com/71880287/126165599-2532586f-9225-4fa2-b749-a57e931fdc64.JPG)

![error_details](https://user-images.githubusercontent.com/71880287/126165821-f2123293-e2f2-4276-a45b-a7052c9dd53b.JPG)

**Comment by ylussaud** [comment]
At least add to run script documentation that the menu contribution of EASE doesn't work with Capella 5.0.0 and higher.

**Comment by ylussaud** [comment]
This is fixed by following commits:
 - fd455047ca0dfefc6d85d554300b42cc40545cb2
 - 6f88076934bf6eb7abaa77dfee49d2f2b7322329
