### ISSUE TITLE
Capella-ExchangeMechanism extraction

### ISSUE THREAD

**Issue by thierry112** [labs4capella/python4capella#133]
This issue known in M2Doc (mentioned in help forum) about extracting echangeMechanism of exchange Items exists as well in python4capella. The get function can't find the attribute.
The reason for extracting is preventing mix between flows and others, as they are permanent and not instantanous.

**Comment by ylussaud** [comment]
The M2Doc thread can be found [here](https://forum.mbse-capella.org/t/mass-views-exports/5422/21).

**Comment by ylussaud** [comment]
The problem is related to the enumeration. In the Python API we should return a String. You can try to replace the method with:

            value =  self.get_java_object().getExchangeMechanism()
            if value is None:
                return value
            else:
                return value.getName()

and the set_exchange_mechanism:

             self.get_java_object().setExchangeMechanism(get_enum_literal("http://www.polarsys.org/capella/core/information/" + capella_version(), "ExchangeMechanism", value))
