### ISSUE TITLE
Contribution - Format, Table generation, and Functions from code

### ISSUE THREAD

**Issue by alDA96** [labs4capella/python4capella#140]
On the following sample script you can find an application to check function allocation completeness for every leaf function on you model.
I also implemented table generation, functions from code and formatting that makes the tables readable. Thus reducing post processing after initially running the code.
[Sample script Function allocation.docx](https://github.com/labs4capella/python4capella/files/9267426/Sample.script.Function.allocation.docx)

**Comment by ylussaud** [comment]
@Sophie-Pl should we add that script to the existing sample scripts ?

**Comment by Sophie-Pl** [comment]
I think so.
Thanks for the contribution.
