### ISSUE TITLE
Remove include error.

### ISSUE THREAD

**Issue by ylussaud** [labs4capella/python4capella#161]
It's possible to remove the error on the EASE include statement reported by PyDev. To do so you need to add the include keyword:

![image](https://user-images.githubusercontent.com/809511/200597135-8e448efb-0920-4002-8fc7-dd7d1729a3ad.png)

This should be documented or configured by Python4Capella.

**Comment by ylussaud** [comment]
this should fix #44.

**Comment by ylussaud** [comment]
This method might be also used to remove other false errors live argv see [documentation](https://github.com/labs4capella/python4capella/#false-errors-in-provided-scripts).

**Comment by stephanelacrampe** [comment]
I tested it, it works so well!! this is great news!!!
