### ISSUE TITLE
PhysicalLink: get_connected_physical_ports does not work

### ISSUE THREAD

**Issue by stephanelacrampe** [labs4capella/python4capella#163]
In Capella.py:
PhysicalLink: get_connected_physical_ports does not work.
The method it calls on the java Object does not exist (getConnectedPhysicalPorts).
I see 2 methods that corresponds to it: 
getSourcePhysicalPort
getTargetPhysicalPort

**Comment by ylussaud** [comment]
Duplicate of #115 which is fixed.
