### ISSUE TITLE
Implement a method get_type for Python Class EObject

### ISSUE THREAD

**Issue by Aurelien-Pin** [labs4capella/python4capella#18]
Python allows to retrieve the type of an element using the command type(elem).
However, the if user want to extract or display this information, the result is difficult to read.
(e.g. "<class '__main__.PhysicalFunction'>")

It is possible to get only the name using "type(elem).__name__" or elem.__class__.__name__ but this is not obvious.
It is better to provide a method which already implement this (get the name of the type)

Finally, when using a script that executes on selection, we do not have the real specialized type of the selected element.

For example: 
elem = EObject(getSelection().getFirstElement())
print (elem.__class__.__name__)

This code will always provide "EObject" as result...

PS: BTW, this method "get_type" will be renamed as "get_element_type" in order to avoid conflict with some Capella element which have an attribute "type"

**Comment by ylussaud** [comment]
In Python you can use obj.__class__.__name__

And to get the specific Python Class of an CapellaElement you can use EObject.get_class():

    selected = None
    specific_cls = EObject.get_class(getSelection().getFirstElement())
    if specific_cls is not None:
        selected = specific_cls(getSelection().getFirstElement())
