### ISSUE TITLE
Extracting the Applied Property values from Interactions

### ISSUE THREAD

**Issue by mm-capella** [labs4capella/python4capella#209]
I have created OABs and OESs in the Operational Analysis layer and am trying to extract the Applied Property value data allocated to the element. This is my code, which returns an empty list for the applied property values. I also had a question about how you could have Property values applied across multiple diagrams, considering I am allocating them to interactions on the OES but they do not appear in the OAB.

model = CapellaModel()
model.open(aird_path)

se = model.get_system_engineering()
op_layer = se.get_operational_analysis()
scen_layer = op_layer.get_all_contents_by_type(Scenario)

for scen in scen_layer:
    print(scen.get_name())    
    
    for sf in scen.get_all_contents_by_type(StateFragment):
        if sf.get_name() is not None:
            print (sf.get_name())
        
    for sm in scen.get_all_contents_by_type(SequenceMessage):
        if sm.get_name() is not None:
            print (sm.get_name())
            print (sm.get_applied_property_values())

**Comment by ylussaud** [comment]
Modifying the semantic model might not create graphical element on a diagram if it's not [synchronized](https://eclipse.dev/sirius/doc/specifier/diagrams/Diagrams.html). I don't know how you could add the semantic element to a diagram at a meaningful position...

Did you also check that the semantic element in both cases is the same ? You might be adding a property value to an element and it's an other element that is represented on the other diagram.

In the [Capella forum for scripting](https://forum.mbse-capella.org/c/scripting-with-capella-python4capella/23) there are a number of posts related to property value:

* [Setting property values with Python4capella](https://forum.mbse-capella.org/t/setting-property-values-with-python4capella/5963)
* [New rather than existing Property Value Group added to new Component](https://forum.mbse-capella.org/t/new-rather-than-existing-property-value-group-added-to-new-component/6909)
* [How to “Apply” existing PVGs and Property values to Capella elements that contain them?](https://forum.mbse-capella.org/t/how-to-apply-existing-pvgs-and-property-values-to-capella-elements-that-contain-them/5660)

Their is also a [sample script](https://github.com/labs4capella/python4capella/blob/master/plugins/Python4Capella/sample_scripts/Export_Property_Values_associated_to_elements_to_xlsx.py) that read property value to extract them to a .xlsx file.

**Comment by mm-capella** [comment]
I was reading through the part on synchronization and confused how you turn it on.

I have also attached how I have added the property value as it is not clear how the (sample script) code is trying to extract it.
![image](https://github.com/labs4capella/python4capella/assets/159106362/e89f2b93-eb9c-48b9-a71c-300aba2c5e32)

This is how I have adjusted my code to incorporate how the property value is being extracted, but nothing is being read and only the Interactions (Sequence Message is printing)

model = CapellaModel()
model.open(aird_path)

# gets the SystemEngineering and print its name
se = model.get_system_engineering()
op_layer = se.get_operational_analysis()
scen_layer = op_layer.get_all_contents_by_type(Scenario)


for scen in scen_layer:
    #print('Activities in Scenario', scen.get_name(), ':')
    print(scen.get_name())    
    allPVs = []
    allSM = se.get_all_contents_by_type(SequenceMessage)

    for sm in allSM:
        for PVName in PVMT.get_p_v_names(sm):
            if pvName not in allPVs:
                all.PVs.append(pvName)
        
    #for sf in scen.get_all_contents():
    for sm in allSM:
        if sm.get_name() is not None:
            print ('Interaction is',sm.get_name())
            for pvName in allPVs:
                print('- Connection is',PVMT.get_p_v_value(sm, PVName))

**Comment by ylussaud** [comment]
The syncronization setting is defined in the diagram description (by Capella developpers). I don't think the end user can change this setting.

The implementation of List in Python4Capella dosn't implement the __str__ method, see this [issue](https://github.com/labs4capella/python4capella/issues/210). You should try to iterate with a for loop to see if the collection is really empty.

**Comment by ylussaud** [comment]
replace:

```
print(pv_name)
```

with
```
for name in pv_name:
    print(name, ' ', PVMT.get_p_v_value(sf, name))
```

The list will print as empty event if it's not. That's why you need to loop oven it.

**Comment by mm-capella** [comment]
Unfortunately, with the change, pv_name seems to be empty.

![image](https://github.com/labs4capella/python4capella/assets/159106362/58763a40-e73e-4525-97e6-e61e56311583)

**Comment by ylussaud** [comment]
Your property value is not applied in a group:

```
     pvs = sf.get_applied_property_values()
    for pv in pvs:
        print(' -', pv.get_name(), pv.get_value())
```

**Comment by mm-capella** [comment]
I have managed to get this working and was wondering if I could extract the corresponding activities/ state fragments for the interactions/ state messages

**Comment by ylussaud** [comment]
I'm not sure what you are trying to do. But if you have this information in the semantic browser view, you can call the query by name:

```
capella_query_by_name(myCapellaElement, "query name", expected_class)
```

for instance

```
capella_query_by_name(capability, "Involved Exchanges", FunctionalExchange)
```
Let me know if it helps.

**Comment by mm-capella** [comment]
So I was extracting interactions from scenarios and obtained the following:
for scen in scen_layer:
    allSM = scen.get_all_contents_by_type(SequenceMessage)
    for sm in allSM:    
        
        pvs = sm.get_applied_property_values()
        if sm.get_name() is not None:
        #sending role and receiving role
            sr = sm.get_sending_instance_role()
            rr = sm.get_receiving_instance_role()
            if sr and rr is not None:
                for pv in pvs:
                    worksheet.cell(row=i, column=1).value = pv.get_value()    
                worksheet.cell(row=i, column=2).value = sm.get_name()
                worksheet.cell(row=i, column=3).value = sr.get_name()
                worksheet.cell(row=i, column=4).value = rr.get_name()               
                worksheet.cell(row=i, column=5).value = scen.get_name()
                worksheet.cell(row=i, column=6).value = sm.get_id()
                i = i+1
I was wondering if there was a way to obtain the activity names that attach to the State Fragments of the sending and receiving instance roles (i.e sending/ receiving activities correlating to the interaction/ Sequence message). It is coming up blank for me.

**Comment by ylussaud** [comment]
You can use something like:

```
interaction_state_e_class = get_e_classifier("http://www.polarsys.org/capella/core/interaction/" + capella_version(), "InstanceRole")
for interaction_state in eInverseByType(rr.get_java_object(), interaction_state_e_class):
    value =  interaction_state.getRelatedAbstractState()
    if value is not None:
        e_object_class = getattr(sys.modules["__main__"], "EObject")
        specific_cls = e_object_class.get_class(value)
        if specific_cls is not None:
            state = specific_cls(value)
```
Some part of the Capella metamodel doesn't exists in the Python API... That's why we need to use Java API.

**Comment by mm-capella** [comment]
I have implemented the code as follows, 

for scen in scen_layer:

    allSM = scen.get_all_contents_by_type(SequenceMessage)
    for sm in allSM:    
        
        pvs = sm.get_applied_property_values()
        if sm.get_name() is not None:
        #sending role and receiving role
            sr = sm.get_sending_instance_role()
            rr = sm.get_receiving_instance_role()
            interaction_state_e_class = get_e_classifier("http://www.polarsys.org/capella/core/interaction/" + capella_version(), "InstanceRole")
            for interaction_state in eInverseByType(rr.get_java_object(), interaction_state_e_class):
                value =  interaction_state.getRelatedAbstractState()
                if value is not None:
                    e_object_class = getattr(sys.modules["__main__"], "EObject")
                    specific_cls = e_object_class.get_class(value)
                    if specific_cls is not None:
                        state = specific_cls(value)
                        print (state)

and tried printing this state value but get the following error:
org.eclipse.ease.ScriptExecutionException: Traceback (most recent call last):
  File "workspace://CRR_Data_Exporting/Export_scenarios_interactions_activities_java.py", line 84, in <module>
AttributeError: 'NoneType' object has no attribute 'get_java_object'

Have I called on the function/ Java API incorrectly or need to integrate the rr value into the java space?

**Comment by ylussaud** [comment]
In some cases sr and rr might be None, you need to add a check before calling anything on them:

```
            if rr is not None:
                for interaction_state in eInverseByType(rr.get_java_object(), interaction_state_e_class):
```

**Comment by mm-capella** [comment]
Has that not been established in the line:
if sr and rr is not None:

Are we calling the correct element with the code?
![image](https://github.com/labs4capella/python4capella/assets/159106362/44bbf796-e1b7-47d3-bd65-1a85d7b3ffd7)
Just to clarify, I have been able to extract the Sequence Message (Communication), Sending instance role (NCO), and Receiving instance role (NSAM) but I am looking to get the Related Function (Check with NSAM + Communicates extent of failure) to the State Fragment.
![image](https://github.com/labs4capella/python4capella/assets/159106362/4ac4aa43-9075-4549-a4e1-814262234d7e)

**Comment by ylussaud** [comment]
You can use:

```
value = interaction_state.getRelatedAbstractFunction()
if value is not None:
    e_object_class = getattr(sys.modules["__main__"], "EObject")
    specific_cls = e_object_class.get_class(value)
    if specific_cls is not None:
        function = specific_cls(value)
```

I forgot this part of your question.

**Comment by mm-capella** [comment]
Thanks, did think I was calling the wrong element but it's still coming up blank.
I was wondering if there was a way to communicate with you and work on the code live.
Really appreciate the help you've provided and believe it would be easier if you could make changes on the spot.

**Comment by ylussaud** [comment]
I'm not sure I can help you more on this topic... You might ask on the [Capella forum](https://forum.mbse-capella.org/c/capella/19) how to navigate between those elements. You need someone that a better understanding of the Capella metamodel than I do.

**Comment by mm-capella** [comment]
No worries! Grateful for all the help and advice you've provided thus far.
