### ISSUE TITLE
Get Capability from Abstract Capability Generalization or another Capability

### ISSUE THREAD

**Issue by Nelson1905** [labs4capella/python4capella#214]
Hello,

Hello I would like to get with my python code **Associated Capability 1 and 2** or associated **Abstract Capability Generalisations** directly from **Capability A, B and C**. I search solutions on forums and the documentation but I didn't found functions, solutions to do that. I tried to cast **Capabilities** and **Abstract Capability Generalisations** (which are traited like EObject in python code) by other types (like Mission, Relation, ...) to use more functions but it doesn’t work either.

Could you share me any leads to resolve that please ?

<img width="392" alt="help5" src="https://github.com/labs4capella/python4capella/assets/162606803/7e433ac6-21ed-4a60-8043-bb0c1b7dda4d">

**Comment by ylussaud** [comment]
You can use the semantic browser query to do this:

```
myOperationalCapability = ...
for capa in capella_query_by_name(myOperationalCapability, "Generalizing Elements", OperationalCapability):
    print(capa, capa.get_java_object())
```

**Comment by Nelson1905** [comment]
Yes, it works thank you !!
