### ISSUE TITLE
Get Incoming and outgoing links from a Component

### ISSUE THREAD

**Issue by Nelson1905** [labs4capella/python4capella#215]
Hi, 

I would like get with my python code **Source** and **Target elements** from **Relation** linked at a **Component**, but I didn't found in documentation functions allowing it.
<img width="662" alt="help6" src="https://github.com/labs4capella/python4capella/assets/162606803/c4065444-8c1b-4930-88d9-6708a89c7406">

I try severals functions like for example `get_incoming_linked_elems()` but I get empty lists or errors.
<img width="452" alt="help7" src="https://github.com/labs4capella/python4capella/assets/162606803/2c82439c-6b84-4d1d-a55e-7d681ed35b59">

Would you have any leads to share with me ?

**Comment by ylussaud** [comment]
This [sample script](https://github.com/labs4capella/python4capella/blob/master/plugins/Python4Capella/sample_scripts/Export_list_of_Requirements_to_xlsx.py) doing this.

**Comment by Nelson1905** [comment]
Thanks you, I saw this script but it not really that my question.  I want to get **Allocating_Requirement** or **Allocated_Requirement** specifically from **Logical Component**. It is possible ?

**Comment by ylussaud** [comment]
I don't have the needed setup to test but the requirement addon of Capella comes with its own semantic browser [queries](https://github.com/eclipse-capella/capella-requirements-vp/blob/master/plugins/org.polarsys.capella.vp.requirements.semantic.browser/plugin.xml):

* On CapellaElement:
  * Allocated Requirements
  * Allocating Requirements
* On Requirement:
  * Allocating Elements
  * Allocated Elements

And you can call them with the Python4Capella API, in you case:

```
myLogicalComponent.get_query_result("Allocated Requirements")
```

**Comment by Nelson1905** [comment]
I already tried it but I got empty lists.

**Comment by ylussaud** [comment]
Do you have a stack trace ? With Java 17 there is an error because EASE doesn't have a java module name declaration. Maybe that's why the list is empty. Also the __str__ method is not implemented correctly for the JavaList class from Python4Capella which might let you think the list is empty but it might not be.

**Comment by Nelson1905** [comment]
When I print the list `print(elt.get_query_result("Allocated Requirements"), len(elt.get_query_result("Allocated Requirements")))` I don't get stack trace error but I got it : 
![image](https://github.com/labs4capella/python4capella/assets/162606803/2f967ef1-fa78-4ec9-be05-67195bc94463)

**Comment by ylussaud** [comment]
Did you include the requirement.py module ?

```
# include needed for the requirement API
include('workspace://Python4Capella/simplified_api/requirement.py')
if False:
    from simplified_api.requirement import *
```
If it's already the case, you can also try:

```
myLogicalComponent.get_query_result("Allocated Requirements", Requirement)
```

Python4Capella automatically wrap Java Object to Python objects and that might be the cause of your issue.

**Comment by ylussaud** [comment]
I didn't knew that... requirements queries are not available by default. Thank you for pointing that to me.
