### ISSUE TITLE
Provide repository for automated installation through equinox.p2.director

### ISSUE THREAD

**Issue by chgio** [labs4capella/python4capella#227]
It would be great to be able to run Python4Capella through Docker, for automated testing in CI pipelines or just containerisation.

The closest thing I've found has been @jamilraichouni 's [contribution to #155](https://github.com/labs4capella/python4capella/issues/155#issuecomment-1296364318), where Py4J is installed through:

```dockerfile
# Install Py4J
ENV PY4J_REPOSITORY=https://eclipse.py4j.org/
RUN eclipse -nosplash -consolelog \
  -application org.eclipse.equinox.p2.director \
  -repository ${PY4J_REPOSITORY} -installIU org.py4j.feature.feature.group
```

...but the released `org.eclipse.python4capella.update.zip` isn't a valid `-repository`; installation instructions do say to download it and install from the local archive, but [p2 director documentation](https://help.eclipse.org/latest/index.jsp?topic=/org.eclipse.platform.doc.isv/guide/p2_director.html) doesn't seem to provide any option to do that.

Thanks in advance!

**Comment by ylussaud** [comment]
Yes the repository is zipped... P2 should be able to consume a zipped update site like it does via the Eclipse GUI.
 I would test an URL like this one:
```
jar:https://github.com/labs4capella/python4capella/releases/download/1.3.0/org.eclipse.python4capella.update.zip!/
```
At least it works with the Eclipse GUI, it's pretty slow since it start by downloading the all archive. Let me know it it works with p2 director.

**Comment by chgio** [comment]
Thank you, I hadn't thought of trying the `jar:<url>!` pattern :sweat_smile:
Works like a charm now!

For documentation, I managed to install with:

```dockerfile
ENV CAPELLA_PATH = /opt/capella-7.0.0
ENV PY4C_REPOSITORY=jar:https://github.com/labs4capella/python4capella/releases/download/1.3.0/org.eclipse.python4capella.update.zip!/
RUN capella -nosplash -consolelog \
    -application org.eclipse.equinox.p2.director \
    -repository ${PY4C_REPOSITORY} -installIU \
    org.eclipse.python4capella.feature.feature.group,org.eclipse.python4capella.commandline.feature.feature.group
RUN mkdir -p /tmp/python4capella && \
    unzip ${CAPELLA_PATH}/capella/plugins/org.eclipse.python4capella_1.3.0.202408221204.jar -d /tmp/python4capella && \
    unzip /tmp/python4capella/zips/Python4Capella.zip -d ${CAPELLA_PATH}/Python4Capella
```

...and to run a sample script on the IFE sample model with:

```sh
cd ${CAPELLA_PATH}/samples && \
    unzip IFE_samplemodel.zip && \
    rm IFE_samplemodel.zip
xvfb-run -s "-screen 0 1280x720x24" \
capella -nosplash -consolelog \
-application org.polarsys.capella.core.commandline.core \
-appid org.eclipse.python4capella.commandline \
-data /tmp/workspace \
-import "${CAPELLA_PATH}/Python4Capella|${CAPELLA_PATH}/samples/In-Flight Entertainment System" \
workspace:/Python4Capella/sample_scripts/List_logical_components_in_console.py " ${CAPELLA_PATH}/samples/In-Flight Entertainment System/In-Flight Entertainment System.aird"
```

Thanks again!
