### ISSUE TITLE
Create documentation of how to create a new Python script in a new project

### ISSUE THREAD

**Issue by Aurelien-Pin** [labs4capella/python4capella#29]
Dedicated section to be added in the Python4Capella User Manual
This should include:
 - creation of a PyDev project
 - referencing Python4Capella project
 - creation of a PyDev module
 - import of required scripts

**Comment by lredor** [comment]
This menu entry is not in the index of the documentation (left panel) 
![image](https://user-images.githubusercontent.com/1825882/130075095-3816ea52-bfd6-483a-bf0b-1d1af8d16459.png)
Maybe it's the only missing thing.

**Comment by ylussaud** [comment]
I'll do that
