### ISSUE TITLE
Embark a Python module which support Excel read and write

### ISSUE THREAD

**Issue by Aurelien-Pin** [labs4capella/python4capella#33]
After implementing https://github.com/labs4capella/python4capella/issues/20, we will need a python module to support excel file read and write

**Comment by ylussaud** [comment]
There are two examples:
- write: [list_physical_components_to_xlsx.py](https://github.com/labs4capella/python4capella/blob/master/plugins/Python4Capella/sample_scripts/list_physical_components_to_xlsx.py)
- read: [import_physical_components_from_xlsx.py](https://github.com/labs4capella/python4capella/blob/master/plugins/Python4Capella/sample_scripts/import_physical_components_from_xlsx.py)
