### ISSUE TITLE
Auto test on CapellaModel provide result KO while relation works

### ISSUE THREAD

**Issue by Aurelien-Pin** [labs4capella/python4capella#38]
Some relation defined on CapellaModel works while auto tests provide KO result.
This is the case for example of "get_system_engineering()", "get_all_diagrams()" and "get_diagrams(diagram_type)".

Auto tests should be improved to avoid false KO result like this

**Comment by ylussaud** [comment]
The constructor of the class CapellaModel need the path for the aird file to be passed. This case is not supported by the generator.

**Comment by ylussaud** [comment]
Is it needed to change the generator ?

**Comment by ylussaud** [comment]
do change the generator for this case.

**Comment by ylussaud** [comment]
You can check the tests results for tests starting by test_CapellaModel_. Some of them are still failing for other reasons.
