### ISSUE TITLE
Create a new custom template

### ISSUE THREAD

**Issue by Aurelien-Pin** [labs4capella/python4capella#42]
When create a new python script, we are prompted with predefined templates.
It would be nice to maybe filter this predefined list, and add a custom Python4Capella template (with predefined imports and stuff like this)

![template](https://user-images.githubusercontent.com/71880287/127185932-39dc6152-f0cd-4d76-8944-6d5682749aa7.JPG)

**Comment by ylussaud** [comment]
This is done:

![image](https://user-images.githubusercontent.com/809511/186915744-26031889-adeb-4ed0-b5ed-e03d47f67a7e.png)
