### ISSUE TITLE
Add shortcuts to create PyDev Project and PyDev Module

### ISSUE THREAD

**Issue by Aurelien-Pin** [labs4capella/python4capella#43]
When using right click in the Project Explorer, PyDev Project and PyDev Module are not directly proposed. We have to go in New Project or Other and browse the full list to find relevant elements

<img width="431" alt="Shortcut" src="https://user-images.githubusercontent.com/71880287/127186522-877df374-8bc0-4df9-bc30-cc4b363e3ae9.png">

**Comment by ylussaud** [comment]
I have them but it might need to enable the development capability...
