### ISSUE TITLE
Fix additional scripts examples

### ISSUE THREAD

**Issue by Aurelien-Pin** [labs4capella/python4capella#59]
Additional examples have been defined based on the user needs defined in https://github.com/labs4capella/python4capella/blob/master/specification/User%20Scripts%20Need%20definition/Additional%20Needs.docx

They are available here:
[User Scripts.zip](https://github.com/labs4capella/python4capella/files/6938672/User.Scripts.zip)

However, most of them does not work:

- Need 1: KO because of https://github.com/labs4capella/python4capella/issues/36
- Need 2: KO because of https://github.com/labs4capella/python4capella/issues/20
- Need 3: KO because of https://github.com/labs4capella/python4capella/issues/56
- Need 3b: KO because of https://github.com/labs4capella/python4capella/issues/56
- Need 4: KO because of https://github.com/labs4capella/python4capella/issues/36
- Need 5: KO because of https://github.com/labs4capella/python4capella/issues/20
- Need 7: KO because of https://github.com/labs4capella/python4capella/issues/64
- Need 8: OK
- Need 9: KO because of https://github.com/labs4capella/python4capella/issues/56 and https://github.com/labs4capella/python4capella/issues/20

Note: scripts for Needs 2 and 5 and 9 have not been defined because it requires to define a Python library to read excel files https://github.com/labs4capella/python4capella/issues/33 (currently not defined)

Note2: Need 6 have been skipped because it requires https://github.com/labs4capella/python4capella/issues/52

**Comment by ylussaud** [comment]
Need1.py, Need3.py, Need4.py, Need7.py, and Need8.py has been fixed an moved to Python4Capella/sample_scripts/. Each script will create a result folder in the selected Capella project, by default IFE with the resulting xlsx file.

For the moment Need3b.py is not fixed since I need some input to use PVMT.

**Comment by ylussaud** [comment]
All scripts are fixed.
