### ISSUE TITLE
LogicalArchitecture's FunctionalChain get involved_functions return None

### ISSUE THREAD

**Issue by xiangqiaolxq** [labs4capella/python4capella#85]
I want get involved functions from a logical function chain, by using express FunctionalChain .get_involved_functions but return None.
I find code run here return None:
class EObject(JavaObject):
    @staticmethod
    def get_class(e_object):
        try:
            res = getattr(sys.modules["__main__"], e_object.eClass().getName())
        except AttributeError:
            res = None
Class LogicalFunction has no eClass()

**Comment by ylussaud** [comment]
Do you have the value of e_object.eClass().getName() and can check if the class exists in capella.py.
Something can be missing in EObject.get_class() to map the Java class to the Python class.

**Comment by ylussaud** [comment]
I fixed this issue by changing the content of FunctionalChain.get_involved_functions() to:

```
    def get_involved_functions(self):
        res = []
        for involvment in self.get_java_object().getOwnedFunctionalChainInvolvements():
            if involvment.eClass().getName() == 'FunctionalChainInvolvementFunction':
                involvedElement = involvment.getInvolvedElement()
                if involvedElement is not None:
                    e_object_class = getattr(sys.modules["__main__"], "EObject")
                    specific_cls = e_object_class.get_class(involvedElement)
                    res.append(specific_cls(involvedElement))
        return res
```
