### ISSUE TITLE
When Running Scripts, Errors come up

### ISSUE THREAD

**Issue by maevans12** [labs4capella/python4capella#87]
When running any python script, the following errors are consistently thrown.  (Running Capella 5.1.0, python4capella release 11-03-2021, python37 (updated pip, installed pandas (which brought in numpy and others) and python-chart), 

null
org.eclipse.ease
Error
Fri Nov 05 09:34:51 CDT 2021
The method name "zip" from the module "__EASE_MOD_org_eclipse_ease_modules_platform_ResourcesModule" can not be wrapped because it's name is reserved

null
org.eclipse.ease
Error
Fri Nov 05 09:34:51 CDT 2021
The method name "zip" from the module "__EASE_MOD_org_eclipse_ease_modules_platform_ResourcesModule" can not be wrapped because it's name is reserved

**Comment by maevans12** [comment]
The script seems to run normally, so issue is a non-blocker.

**Comment by ylussaud** [comment]
I also noticed this error message with Capella 5.1.0. It seems to come from an EASE module that expose a method zip().
