### ISSUE TITLE
Preferences/PyDev/Interpreters/Python Interpreter does not show installed python packages until after update of pip

### ISSUE THREAD

**Issue by maevans12** [labs4capella/python4capella#88]
The default version of pip that comes with the Python37 install .zip comes with pip version 21.2.4.  When you configure the interpreters in Capella, the packages did not get listed in the Packages window (even after several restarts of Capella 5.1.0).  Once pip was updated to 21.3.1, then the packages are listed.

This issue does not seem to affect whether scripts run or not, just observed behavior.

**Comment by maevans12** [comment]
![image](https://user-images.githubusercontent.com/18238582/140530588-c327b6e1-29d7-4cce-b18f-94eea6f02a78.png)
This is what the window looks like prior to updated pip.

**Comment by maevans12** [comment]
![image](https://user-images.githubusercontent.com/18238582/140530697-5e9bcabf-78c5-4f3e-94cb-140949ae708e.png)
AFter updating pip.

**Comment by ylussaud** [comment]
see discussion #84 to update the documentation and fix the Python37.zip file.

**Comment by ylussaud** [comment]
This is documented.
